In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

## Creating Numpy Array

In [3]:
list1 = [1,2,3,4,5,6,7,9]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 9]


In [4]:
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 9])

In [5]:
arr1.shape

(8,)

In [6]:
arr1.ndim

1

In [7]:
list2 = [
    [1,2,3,4],
    [5,6,7,9]
]
print(list2)

[[1, 2, 3, 4], [5, 6, 7, 9]]


In [8]:
arr2 = np.array(list2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

In [9]:
arr2.shape

(2, 4)

In [10]:
arr2.ndim

2

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [11]:
np.zeros(shape=(2,2), dtype = "int")

array([[0, 0],
       [0, 0]])

In [12]:
np.full(shape = (4,5), fill_value = 2_00)

array([[200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200]])

In [16]:
np.arange(1, 90, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81])

In [19]:
arr3 = np.linspace((1, 10) ,(10, 20), num = 5)
arr3

array([[ 1.  , 10.  ],
       [ 3.25, 12.5 ],
       [ 5.5 , 15.  ],
       [ 7.75, 17.5 ],
       [10.  , 20.  ]])

In [20]:
np.diag([2,4,5])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [21]:
np.identity(n = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
import random

random.randint(1,10)

10

In [24]:
np.random.randint(0,50, size = (2,2))

array([[44, 25],
       [12, 37]])

In [30]:
np.random.randint(0,50, size = (3,3,2,5))

array([[[[33,  5, 17, 25, 26],
         [39, 11, 22, 24,  7]],

        [[24, 38, 24, 29, 31],
         [ 8,  3,  8, 11, 27]],

        [[32, 23, 48, 27, 24],
         [27, 30, 19, 40, 33]]],


       [[[11, 20, 40, 14, 47],
         [44, 16, 16, 22, 15]],

        [[13, 47, 23, 45, 16],
         [ 2,  9,  4, 21, 23]],

        [[39, 23,  4, 16, 16],
         [10, 26, 30,  4, 34]]],


       [[[36, 39, 12, 17, 47],
         [15, 16, 47, 22,  3]],

        [[13, 10,  4, 17,  2],
         [ 4,  7, 24,  0, 34]],

        [[ 2,  0, 21, 37, 14],
         [14, 10, 41, 17,  5]]]])

In [33]:
np.random.rand(2,5,4)

array([[[0.21427247, 0.56245218, 0.39793986, 0.09016721],
        [0.92066073, 0.99290635, 0.0968466 , 0.06669387],
        [0.65418715, 0.82164897, 0.78793788, 0.79746845],
        [0.73595581, 0.93392991, 0.33973435, 0.51113561],
        [0.2536865 , 0.89136142, 0.42559271, 0.97856192]],

       [[0.61904129, 0.54169068, 0.92592136, 0.87692211],
        [0.82668073, 0.10278074, 0.27785985, 0.63275915],
        [0.21402136, 0.40169565, 0.06756529, 0.19765575],
        [0.6804179 , 0.6507423 , 0.72129512, 0.77176467],
        [0.09522859, 0.79806926, 0.31731099, 0.28935557]]])

## Accessing an Array

## Indexing and Slicing NumPy Arrays

NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

### Indexing:

Indexing follows a simple rule that we may have encountered before. Let's give it a try.

- 1D Array: array_name[idx] (Similar to Python list)
- 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
- ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

**OR**

- 2D Array: array_name[row_idx][col_idx]
- ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]


 ### Slicing:

Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

- 1D Array: array_name[idx1:idx2:step]
- 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
- ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [36]:
# 1d
a = np.array([1,2,3,4,5])

In [38]:
a[-3]

np.int64(3)

In [40]:
a[0:3:1]

array([1, 2, 3])

In [46]:
#2d
b = np.random.randint(0,20, size = (5,4))
b

array([[ 3, 19, 16,  6],
       [18, 17,  3, 14],
       [11, 17,  3,  7],
       [12, 13,  9, 12],
       [14,  2, 16,  2]])

In [ ]:
b[1, 0] # b[1][0]

np.int64(18)

In [ ]:
b[-2] 

array([12, 13,  9, 12])

In [ ]:
# Slicing 2D array : (array[<row_slice>, <col_slice>])
b[::2, 2::]

array([[16,  6],
       [ 3,  7],
       [16,  2]])

In [64]:
b[:2, 1]

array([19, 17])

In [ ]:
#3d
c = np.random.randint(0,20, size = (3, 3,4))
c

array([[[ 3, 19,  6, 19],
        [ 1,  1,  8, 15],
        [ 4,  4,  4, 13]],

       [[ 0, 13,  6,  0],
        [14,  1,  8, 15],
        [ 1,  9,  5,  9]],

       [[13, 10,  3,  8],
        [ 3,  8, 11,  9],
        [19, 14, 13,  6]]])

In [ ]:
c[0, 1, 2]

np.int64(8)

In [ ]:
c[0:2:1, 0:2 , 2:]

array([[[ 6, 19],
        [ 8, 15]],

       [[ 6,  0],
        [ 8, 15]]])

In [78]:
# 20 colorful images
c = np.random.randint(0,255, size = (20, 3, 720, 720))

In [77]:
c.shape

(20, 3, 32, 32)