In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

## Creating Numpy Array

In [21]:
list1 = [1,2,3,4,5,6,7,9]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 9]


In [22]:
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 9])

In [23]:
arr1.shape

(8,)

In [14]:
arr1.ndim

1

In [15]:
list2 = [
    [1,2,3,4],
    [5,6,7,9]
]
print(list2)

[[1, 2, 3, 4], [5, 6, 7, 9]]


In [16]:
arr2 = np.array(list2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

In [17]:
arr2.shape

(2, 4)

In [24]:
arr2.ndim

2

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [ ]:
np.zeros(shape=(2,2), dtype = "int")

array([[0, 0],
       [0, 0]])

In [28]:
np.zeros(shape=(3,10,10), dtype = "int")

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [32]:
np.full(shape = (4,5), fill_value = 2_00)

array([[200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200]])