## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.concatenate()`: Method to concatenate two or more arrays
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [2]:
import numpy as np

In [3]:
arr = np.random.rand(10,50)

In [4]:
arr.shape

(10, 50)

In [5]:
arr.ndim

2

In [6]:
arr.dtype

dtype('float64')

In [ ]:
arr.size # Number of elements

500

In [ ]:
arr_T = arr.T # Matrix Transpose ( rows to columns , and columns to row)
arr_T.shape

(50, 10)

In [26]:
arr = np.random.randint(1,5, (3,4))
arr

array([[4, 3, 3, 2],
       [4, 3, 2, 1],
       [1, 2, 3, 2]])

In [27]:
arr.reshape(2,3,-1)

array([[[4, 3],
        [3, 2],
        [4, 3]],

       [[2, 1],
        [1, 2],
        [3, 2]]])

In [28]:
flat_arry = arr.flatten()
flat_arry

array([4, 3, 3, 2, 4, 3, 2, 1, 1, 2, 3, 2])

In [31]:
# Axis-Specific Sum: You can sum across rows or columns:
#     axis=0: Calculates the sum column-wise (collapses rows).
#     axis=1: Calculates the sum row-wise (collapses columns).

# arr.sum(axis=1)
# arr.sum(axis=0)
arr.sum()

np.int64(30)

In [34]:
arr.prod(axis = 1)

array([72, 24, 12])

In [36]:
arr.cumsum(axis = 1)

array([[ 4,  7, 10, 12],
       [ 4,  7,  9, 10],
       [ 1,  3,  6,  8]])

In [37]:
arr.max()

np.int64(4)

In [39]:
arr.min(axis = 1)

array([2, 1, 1])

In [42]:
arr.argmax(axis = 1)

array([0, 0, 2])

In [53]:
arr1 = np.random.randint(1,100, (3,3))
arr2 = np.random.randint(1,100, (3,2))

In [54]:
arr1

array([[46, 79,  6],
       [24,  3, 78],
       [60, 96, 64]])

In [55]:
arr2

array([[40, 97],
       [17, 96],
       [74, 15]])

In [ ]:
merged = np.concatenate([arr1, arr2], axis = 1)
merged

array([[46, 79,  6, 40, 97],
       [24,  3, 78, 17, 96],
       [60, 96, 64, 74, 15]])

In [61]:
np.vstack([arr1, arr2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [59]:
np.hstack([arr1, arr2])

array([[46, 79,  6, 40, 97],
       [24,  3, 78, 17, 96],
       [60, 96, 64, 74, 15]])