In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,6, (2,3))
b = np.random.randint(6,10, (3,3))
c = np.random.randint(1,9, (3,3))

In [11]:
b,c

(array([[7, 9, 8],
        [6, 9, 9],
        [7, 8, 9]]),
 array([[7, 6, 1],
        [3, 3, 6],
        [8, 4, 8]]))

## 1. Elementwise Operations

### Arithmetic Operations

In [9]:
# b + c
np.add(b,c)

array([[14, 15,  9],
       [ 9, 12, 15],
       [15, 12, 17]])

In [10]:
# b - c
np.subtract(b,c)

array([[ 0,  3,  7],
       [ 3,  6,  3],
       [-1,  4,  1]])

In [14]:
# b * c
np.multiply(b,c)

array([[49, 54,  8],
       [18, 27, 54],
       [56, 32, 72]])

In [17]:
# b % c
np.mod(b,c)

array([[0, 3, 0],
       [0, 0, 3],
       [7, 0, 1]])

In [21]:
# a ** 2
np.pow(b, 2)

array([[49, 81, 64],
       [36, 81, 81],
       [49, 64, 81]])

### Trignometric

In [22]:
np.sin(a)

array([[ 0.84147098,  0.90929743, -0.95892427],
       [-0.95892427, -0.95892427, -0.7568025 ]])

In [23]:
cot = 1 /np.tan(b)
cot

array([[ 1.14751542, -2.21084541, -0.14706506],
       [-3.436353  , -2.21084541, -2.21084541],
       [ 1.14751542, -0.14706506, -2.21084541]])

### Rounding operations

In [24]:
np.around(cot, 2)

array([[ 1.15, -2.21, -0.15],
       [-3.44, -2.21, -2.21],
       [ 1.15, -0.15, -2.21]])

In [26]:
np.floor(cot)

array([[ 1., -3., -1.],
       [-4., -3., -3.],
       [ 1., -1., -3.]])

In [25]:
np.ceil(cot)

array([[ 2., -2., -0.],
       [-3., -2., -2.],
       [ 2., -0., -2.]])

## 2. Matrix Operations


In [44]:
a = np.random.randint(1,50, (20,30))
b = np.random.randint(6,100, (3,3))

In [38]:
# MAtrix Multiplication

# a @ b

# np.dot(a,b)

res = a.dot(b)

In [39]:
res.shape

(20, 30)

In [45]:
# Inverse of a matrix

deter = np.linalg.det(b)
inv = np.linalg.inv(b)

In [46]:
inv

array([[-0.00149295,  0.0447332 , -0.03610727],
       [-0.0069671 , -0.12457838,  0.16483273],
       [ 0.02576721,  0.07978988, -0.11755599]])

In [ ]:
# Prove A * A^-1 = I
np.dot(b, inv).round()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])